version: '3.8'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/app/static/
    depends_on:
      - db
    restart: on-failure
    ports:
      - 8000:8000
